### PR TITLE
Make security bundle optional

### PR DESCRIPTION
**Pull request by cedvan**
Just make **symfony/security-bundle optional**

*Bonus : Add binary folder to composer*

### CODE REVIEW

**Comment by omansour** [comment]
:-1: test are failing

**Comment by cedvan** [comment]
@omansour Tests ok on local. I looked build, config Travis is bad ?

**Comment by mikaelrandy** [comment]
@cedvan you have to update theses 2 lines to follow composer bin dir update : https://github.com/M6Web/LogBridgeBundle/blob/master/.travis.yml#L14-L15

**Comment by omansour** [comment]
funny-pictures-cat-disguised-rabbit

yeah ! not related at all :)

**Comment by cedvan** [comment]
@omansour :joy:, tests ok ;)

**Comment by mikaelrandy** [comment]
:+1:

**Comment by lnahiro** [comment]
:+1:

**Comment by cedvan** [comment]
New release [3.0.1](https://github.com/M6Web/LogBridgeBundle/releases/tag/v3.0.1)

**Pull request merged**
