### PR TITLE
Use tokenStorage instead of deprecated SecurityContext in defaultFormater

### PR DESCRIPTION
**Pull request by mojoLyon**
Must release this as major.

### CODE REVIEW

**Comment by fabdsp** [comment]
:+1:

**Comment by b-viguier** [comment]
:+1:

**Comment by omansour** [comment]
:+1: it's an improvment with no BC break. raise up juste the middle number ? v2.3.0

**Comment by mojoLyon** [comment]
SecurityContext is deprec

**Comment by mikaelrandy** [comment]
@omansour a public method change : possible BC break => mahor

**Comment by mikaelrandy** [comment]
:+1:

**Comment by omansour** [comment]
@mikaelrandy right !

**Comment by mikaelrandy** [comment]
A require will install symfony/security 2.6+. Do we really need it ?

**Comment by mojoLyon** [comment]
@mikaelrandy The TokenStorage is in this package : https://github.com/symfony/Security/blob/master/Core/Authentication/Token/Storage/TokenStorage.php

**Comment by mikaelrandy** [comment]
:+1:

**Pull request merged**
